import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedSignupWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedSignupWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedLoginWidget2.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedLoginWidget3.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedLoginWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio2widget/generated/GeneratedForgotPasswordWidget.dart';

/* Frame Radio2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadio2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 119.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 103.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 50.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 151.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 35.0,
                child: GeneratedSignupWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 67.0,
                child: GeneratedLoginWidget1(),
              ),
              Positioned(
                left: 52.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 32.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 119.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 103.0,
                child: GeneratedLoginWidget2(),
              ),
              Positioned(
                left: 132.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 50.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 151.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 35.0,
                child: GeneratedSignupWidget1(),
              ),
              Positioned(
                left: 132.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 50.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 145.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 67.0,
                child: GeneratedLoginWidget3(),
              ),
              Positioned(
                left: 51.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 33.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 220.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 20.0,
                child: GeneratedForgotPasswordWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 2.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 2.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 231.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 292.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 116.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 7.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 116.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 7.0,
                child: GeneratedLine9Widget(),
              )
            ]),
      ),
    ));
  }
}
