import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedAlreadyhaveanaccountWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedTwitterWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedMailWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLockWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedVectorWidget11.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedFacebookWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLinkedinWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLine9Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedOrsignupwithWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLockWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLoginWidget4.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedSIGNUPWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedLoginWidget5.dart';
import 'package:flutterapp/fmradioapp/generatedradio3widget/generated/GeneratedRectangle2Widget.dart';

/* Frame Radio3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadio3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 132.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 50.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 144.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 67.0,
                child: GeneratedLoginWidget4(),
              ),
              Positioned(
                left: 22.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 2.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 2.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 87.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 103.0,
                child: GeneratedSIGNUPWidget(),
              ),
              Positioned(
                left: 109.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 50.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 132.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 55.0,
                child: GeneratedSIGNUPWidget1(),
              ),
              Positioned(
                left: 56.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 33.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 56.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 33.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 56.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 30.0,
                child: GeneratedConfirmPasswordWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 2.0,
                child: GeneratedLine5Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 2.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 2.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 21.0,
                child: GeneratedMailWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedLockWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedLockWidget1(),
              ),
              Positioned(
                left: 60.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 23.0,
                child: GeneratedAlreadyhaveanaccountWidget(),
              ),
              Positioned(
                left: 267.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 60.0,
                child: GeneratedLoginWidget5(),
              ),
              Positioned(
                left: 130.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 23.0,
                child: GeneratedOrsignupwithWidget(),
              ),
              Positioned(
                left: 108.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFacebookWidget(),
              ),
              Positioned(
                left: 160.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedTwitterWidget(),
              ),
              Positioned(
                left: 210.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedLinkedinWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.052;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.5;

                  double percentHeight = 0.025895064687493988;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      21.026792526245117;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6933333333333334,
                        translateY: constraints.maxHeight * 0.7955665024630542,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget11())
                  ]);
                }),
              ),
              Positioned(
                left: 257.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 292.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 43.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 253.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 43.0,
                child: GeneratedEllipse7Widget(),
              ),
              Positioned(
                left: 203.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 43.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 43.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 86.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 7.0,
                child: GeneratedLine9Widget1(),
              )
            ]),
      ),
    ));
  }
}
