import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedRectangle30Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedRectangle5Widget11.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse19Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedRectangle15Widget11.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedVectorWidget205.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedRectangle14Widget11.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse8Widget11.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedAlignjustifyWidget9.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedFastforwardWidget17.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedRectangle28Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedLine11Widget11.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse24Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse9Widget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse12Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedUploadWidget10.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse11Widget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse21Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedFastforwardWidget16.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedFolderWidget10.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedVolumexWidget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedLine10Widget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse20Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedEllipse23Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio15widget/generated/GeneratedRectangle31Widget.dart';

/* Frame Radio15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadio15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 116.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 70.0,
                child: GeneratedRectangle5Widget11(),
              ),
              Positioned(
                left: 308.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 51.0,
                child: GeneratedEllipse8Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 8.0,
                child: GeneratedRectangle14Widget11(),
              ),
              Positioned(
                left: 6.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAlignjustifyWidget9(),
              ),
              Positioned(
                left: 78.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 242.0,
                child: GeneratedEllipse9Widget8(),
              ),
              Positioned(
                left: 62.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 252.00198364257812,
                height: 2.0,
                child: GeneratedLine10Widget8(),
              ),
              Positioned(
                left: 153.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 17.0,
                child: GeneratedEllipse11Widget8(),
              ),
              Positioned(
                left: 27.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVolumexWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle15Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine11Widget11(),
              ),
              Positioned(
                left: 323.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolderWidget10(),
              ),
              Positioned(
                left: 14.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUploadWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 217.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 252.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle28Widget1(),
              ),
              Positioned(
                left: 147.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle20Widget1(),
              ),
              Positioned(
                left: 41.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle30Widget1(),
              ),
              Positioned(
                left: 323.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse21Widget1(),
              ),
              Positioned(
                left: 254.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse20Widget1(),
              ),
              Positioned(
                left: 179.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse19Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse23Widget1(),
              ),
              Positioned(
                left: 160.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 7.0,
                child: GeneratedLine12Widget(),
              ),
              Positioned(
                left: 153.169921875,
                top: 506.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 65.0,
                child: GeneratedEllipse12Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04533333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 17.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.47733333333333333,
                        translateY: constraints.maxHeight * 0.6496305418719212,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget205())
                  ]);
                }),
              ),
              Positioned(
                left: 127.99951171875,
                top: 551.6563110351562,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFastforwardWidget16(),
              ),
              Positioned(
                left: 247.0,
                top: 527.5,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFastforwardWidget17(),
              ),
              Positioned(
                left: 104.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse24Widget(),
              )
            ]),
      ),
    ));
  }
}
