import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedUploadWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedAlignjustifyWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedVolumexWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedFastforwardWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedFolderWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedEllipse8Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedFastforwardWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio5widget/generated/GeneratedLine11Widget.dart';

/* Frame Radio5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadio5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 116.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 70.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 308.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 51.0,
                child: GeneratedEllipse8Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 8.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 6.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAlignjustifyWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 242.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 252.00198364257812,
                height: 2.0,
                child: GeneratedLine10Widget(),
              ),
              Positioned(
                left: 153.1697998046875,
                top: 513.5,
                right: null,
                bottom: null,
                width: 66.0,
                height: 65.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 17.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVolumexWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine11Widget(),
              ),
              Positioned(
                left: 323.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolderWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUploadWidget(),
              ),
              Positioned(
                left: 259.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFastforwardWidget(),
              ),
              Positioned(
                left: 115.99951171875,
                top: 558.1563110351562,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFastforwardWidget1(),
              )
            ]),
      ),
    ));
  }
}
