import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio4widget/generated/GeneratedRectangle12Widget.dart';

/* Frame Radio4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadio4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 116.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 70.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 308.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 51.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 140.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 199.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 140.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 140.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 205.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 140.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 140.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 205.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 140.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 140.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 199.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 140.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 8.0,
                child: GeneratedRectangle14Widget(),
              )
            ]),
      ),
    ));
  }
}
