import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedMenuWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle14Widget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse23Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle18Widget2.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedProfileWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedLine11Widget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedUploadWidget7.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedLine11Widget7.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle15Widget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse19Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle5Widget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedAboutWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse18Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedAddWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedLogoutWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse15Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedMailWidget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse16Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse22Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedShareWidget1.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedArrowleftWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse20Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedFolderWidget7.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse17Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedEllipse8Widget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedRectangle15Widget7.dart';
import 'package:flutterapp/fmradioapp/generatedradio14widget/generated/GeneratedLine15Widget.dart';

/* Frame Radio14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadio14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 116.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 70.0,
                child: GeneratedRectangle5Widget8(),
              ),
              Positioned(
                left: 308.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 51.0,
                child: GeneratedEllipse8Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 8.0,
                child: GeneratedRectangle14Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle15Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine11Widget7(),
              ),
              Positioned(
                left: 323.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolderWidget7(),
              ),
              Positioned(
                left: 14.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUploadWidget7(),
              ),
              Positioned(
                left: 176.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMailWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: -12.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 759.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: -12.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 759.0,
                child: GeneratedRectangle18Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 28.0,
                child: GeneratedMenuWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 28.0,
                child: GeneratedAddWidget1(),
              ),
              Positioned(
                left: 7.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrowleftWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 28.0,
                child: GeneratedProfileWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 28.0,
                child: GeneratedAboutWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 28.0,
                child: GeneratedShareWidget1(),
              ),
              Positioned(
                left: 51.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 38.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 71.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 28.0,
                child: GeneratedLogoutWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle15Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine11Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 217.0,
                child: GeneratedRectangle18Widget2(),
              ),
              Positioned(
                left: 252.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 147.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse13Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse14Widget(),
              ),
              Positioned(
                left: 213.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse15Widget(),
              ),
              Positioned(
                left: 284.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse16Widget(),
              ),
              Positioned(
                left: 342.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse17Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 252.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse18Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse19Widget(),
              ),
              Positioned(
                left: 213.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse20Widget(),
              ),
              Positioned(
                left: 284.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse21Widget(),
              ),
              Positioned(
                left: 342.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse22Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse23Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 617.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 7.0,
                child: GeneratedLine15Widget(),
              )
            ]),
      ),
    ));
  }
}
