import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedEllipse11Widget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedAlignjustifyWidget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedEllipse8Widget9.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedFolderWidget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedVectorWidget156.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedVolume2Widget5.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedLine10Widget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedLine11Widget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedRectangle15Widget9.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedFastforwardWidget13.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedVolumexWidget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedEllipse10Widget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedRectangle14Widget9.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedUploadWidget8.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedRectangle5Widget9.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedFastforwardWidget12.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedMailWidget9.dart';
import 'package:flutterapp/fmradioapp/generatedradio11widget/generated/GeneratedEllipse9Widget6.dart';

/* Frame Radio11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadio11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 116.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 70.0,
                child: GeneratedRectangle5Widget9(),
              ),
              Positioned(
                left: 308.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 51.0,
                child: GeneratedEllipse8Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 8.0,
                child: GeneratedRectangle14Widget9(),
              ),
              Positioned(
                left: 6.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAlignjustifyWidget6(),
              ),
              Positioned(
                left: 78.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 242.0,
                child: GeneratedEllipse9Widget6(),
              ),
              Positioned(
                left: 62.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 252.00198364257812,
                height: 2.0,
                child: GeneratedLine10Widget6(),
              ),
              Positioned(
                left: 153.1697998046875,
                top: 513.5,
                right: null,
                bottom: null,
                width: 66.0,
                height: 65.0,
                child: GeneratedEllipse10Widget6(),
              ),
              Positioned(
                left: 153.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 17.0,
                child: GeneratedEllipse11Widget6(),
              ),
              Positioned(
                left: 27.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVolumexWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle15Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine11Widget9(),
              ),
              Positioned(
                left: 323.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolderWidget8(),
              ),
              Positioned(
                left: 14.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUploadWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04533333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 17.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.47733333333333333,
                        translateY: constraints.maxHeight * 0.6588669950738916,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget156())
                  ]);
                }),
              ),
              Positioned(
                left: 176.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMailWidget9(),
              ),
              Positioned(
                left: 127.99951171875,
                top: 559.1563110351562,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFastforwardWidget12(),
              ),
              Positioned(
                left: 247.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFastforwardWidget13(),
              ),
              Positioned(
                left: 323.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVolume2Widget5(),
              )
            ]),
      ),
    ));
  }
}
