import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedRectangle15Widget12.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedAlignjustifyWidget10.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse9Widget9.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse29Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedRectangle5Widget12.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedFastforwardWidget19.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedFolderWidget12.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse25Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedUploadWidget12.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse26Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedFolderWidget11.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse11Widget9.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse10Widget8.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse30Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedVolumexWidget9.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedVolume2Widget8.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedVolumexWidget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedLine15Widget1.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedMailWidget12.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedUploadWidget11.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse27Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedLine10Widget9.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedLine11Widget12.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse28Widget.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedRectangle14Widget12.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedVectorWidget221.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedEllipse8Widget12.dart';
import 'package:flutterapp/fmradioapp/generated16widget/generated/GeneratedFastforwardWidget18.dart';

/* Frame 16
    Autogenerated by FlutLab FTF Generator
  */
class Generated16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 116.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 70.0,
                child: GeneratedRectangle5Widget12(),
              ),
              Positioned(
                left: 308.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 51.0,
                child: GeneratedEllipse8Widget12(),
              ),
              Positioned(
                left: 0.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 8.0,
                child: GeneratedRectangle14Widget12(),
              ),
              Positioned(
                left: 6.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAlignjustifyWidget10(),
              ),
              Positioned(
                left: 78.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 242.0,
                child: GeneratedEllipse9Widget9(),
              ),
              Positioned(
                left: 62.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 252.00198364257812,
                height: 2.0,
                child: GeneratedLine10Widget9(),
              ),
              Positioned(
                left: 153.1697998046875,
                top: 513.5,
                right: null,
                bottom: null,
                width: 66.0,
                height: 65.0,
                child: GeneratedEllipse10Widget8(),
              ),
              Positioned(
                left: 153.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 17.0,
                child: GeneratedEllipse11Widget9(),
              ),
              Positioned(
                left: 27.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVolumexWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle15Widget12(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine11Widget12(),
              ),
              Positioned(
                left: 323.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolderWidget11(),
              ),
              Positioned(
                left: 14.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUploadWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04533333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 17.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.47733333333333333,
                        translateY: constraints.maxHeight * 0.6588669950738916,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget221())
                  ]);
                }),
              ),
              Positioned(
                left: 176.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMailWidget12(),
              ),
              Positioned(
                left: 127.99951171875,
                top: 559.1563110351562,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFastforwardWidget18(),
              ),
              Positioned(
                left: 247.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFastforwardWidget19(),
              ),
              Positioned(
                left: 325.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVolume2Widget8(),
              ),
              Positioned(
                left: 62.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 252.00198364257812,
                height: 2.0,
                child: GeneratedLine13Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 17.0,
                child: GeneratedEllipse25Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVolumexWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle32Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine14Widget(),
              ),
              Positioned(
                left: 323.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolderWidget12(),
              ),
              Positioned(
                left: 14.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUploadWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 217.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 252.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 147.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 65.0,
                child: GeneratedRectangle36Widget(),
              ),
              Positioned(
                left: 323.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse26Widget(),
              ),
              Positioned(
                left: 254.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse27Widget(),
              ),
              Positioned(
                left: 179.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse28Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse29Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 7.0,
                child: GeneratedLine15Widget1(),
              ),
              Positioned(
                left: 104.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 50.0,
                child: GeneratedEllipse30Widget(),
              )
            ]),
      ),
    ));
  }
}
