import 'package:flutter/material.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedRectangle5Widget7.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedLogoutWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedAddWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedUploadWidget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedEllipse8Widget7.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedMailWidget7.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedShareWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedAboutWidget.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedRectangle14Widget7.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedLine11Widget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedFolderWidget6.dart';
import 'package:flutterapp/fmradioapp/generatedradio13widget/generated/GeneratedMenuWidget.dart';

/* Frame Radio13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadio13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 29, 230, 85),
              Color.fromARGB(147, 167, 201, 31)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 116.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 70.0,
                child: GeneratedRectangle5Widget7(),
              ),
              Positioned(
                left: 308.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 51.0,
                child: GeneratedEllipse8Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 8.0,
                child: GeneratedRectangle14Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle15Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine11Widget6(),
              ),
              Positioned(
                left: 323.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolderWidget6(),
              ),
              Positioned(
                left: 14.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUploadWidget6(),
              ),
              Positioned(
                left: 176.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMailWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 759.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 759.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 28.0,
                child: GeneratedMenuWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 28.0,
                child: GeneratedAddWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 28.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 28.0,
                child: GeneratedAboutWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 28.0,
                child: GeneratedShareWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 689.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 38.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 28.0,
                child: GeneratedLogoutWidget(),
              )
            ]),
      ),
    ));
  }
}
